Repository OctopusDeploy/Library, pull requests merged in 2019-12, with the labels that each got.

#838 Add Pulumi Step Template to be used for Windows workers
  step-templates/run-pulumi-on-linux.json
  step-templates/run-pulumi-on-windows.json
Labels: cla-signed, pr-reviewed

#837 Update hosts file
  gulpfile.babel.js
  step-templates/logos/hosts-file.png
  step-templates/update-hosts-file.json
Labels: cla-signed, pr-reviewed

#840 Fix scheduled-task-changepath for Server 2012
  step-templates/windows-scheduled-task-changepath.json
Labels: cla-signed, feedback-required

#842 Configure SecurityProtocols to be used as part of the web requests to AppInsights
  step-templates/application-insights-annotate-release.json
Labels: cla-signed

#839 Made the wait verbose.(Countdown timer in place)
  step-templates/wait.json
Labels: cla-signed
