Repository OctopusDeploy/Library, pull requests merged in 2020-04, with the labels that each got.

#896 Lets Encrypt - Azure DNS and update for AWS Route53
  step-templates/letsencrypt-azure-dns.json
  step-templates/letsencrypt-route-53.json
Labels: cla-exempt

#897 Force TLS 1.2 for http test url step template
  step-templates/http-test-url.json
Labels: cla-exempt

#899 Bug: Exported default value breaks sync.
  step-templates/letsencrypt-route-53.json
Labels: bug, cla-exempt

#904 Bug: Set TLS 1.2 to enable steps to run on Dynamic Workers.
  step-templates/letsencrypt-azure-dns.json
  step-templates/letsencrypt-cloudflare.json
  step-templates/letsencrypt-google-cloud.json
  step-templates/letsencrypt-route-53.json
Labels: bug, cla-exempt

#902 Force TLS 1.2 for app insights step template
  step-templates/application-insights-annotate-release.json
Labels: cla-exempt

#905 Added Twilio - Send Message (PowerShell)
  gulpfile.babel.js
  step-templates/logos/twilio.png
  step-templates/twilio-send-sms-powershell.json
Labels: cla-exempt

#903 Adding step templates exported from https://samples.octopus.app which…
  step-templates/azure-create-resource-group-az-module.json
  step-templates/azure-delete-resource-group-az-module.json
  step-templates/azure-delete-resource-group.json
  step-templates/octopus-delete-machine-registration.json
  step-templates/octopus-register-aks-k8s-cluster.json
  step-templates/octopus-register-listening-target.json
  step-templates/octopus-register-listening-worker.json
  step-templates/redgate-create-database-release-worker-friendly.json
  step-templates/redgate-deploy-database-release-worker-friendly.json
Labels: waiting-for-changes

#908 Make User parameter optional - not required in New Relic API
  step-templates/newrelic-complete-deployment.json
Labels: waiting-for-changes
